// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package rdb

var TableNames = struct {
	PostComments string
	Posts        string
	Users        string
}{
	PostComments: "post_comments",
	Posts:        "posts",
	Users:        "users",
}
