// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type AddCommentInput struct {
	PostID  string `json:"postId"`
	Content string `json:"content"`
}

type AddCommentPayload struct {
	Comment *Comment `json:"comment"`
}

type AddPostInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type AddPostPayload struct {
	Post *Post `json:"post"`
}

type SignInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignInPayload struct {
	Result bool `json:"result"`
}

type SignUpInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignUpPayload struct {
	Result bool `json:"result"`
}
