# .gqlgen.yml example
#
# Refer to https://gqlgen.com/config/
# for detailed .gqlgen.yml documentation.

schema:
- api/schema/**/*.graphql
exec:
  filename: internal/graphql/generated.go
model:
  filename: internal/graphql/models_gen.go
autobind: []
models:
  User:
    model: github.com/stobita/graphql-golang-example/internal/graphql.User
  Post:
    model: github.com/stobita/graphql-golang-example/internal/graphql.Post
  Comment:
    model: github.com/stobita/graphql-golang-example/internal/graphql.Comment

